/**
 Author: Mahdi Jaberzadeh Ansari
 Email: mahdijaberzadehansari@yahoo.co.uk
 Library: FarsiGradJS
 Description: By using this library you can create gradient colored text in Persian (Farsi) or Arabic sentences.
 Licence: MIT Licence
 Version 1.0.0
 Date: 22 Sep 2016
 */
function FarsiGradientText(a,b,c){function e(a,b){Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){for(var c=b||0,d=this.length;c<d;c++)if(this[c]===a)return c;return-1});var c=new Array("آ","ا","ٱ","أ","إ","ؤ","ء","د","ذ","ر","ز","ژ","و"),e=new Array("آ","ا","أ","إ"),f=new Array("‌"," "," ","\t","\n","\v","\r"),g=new Array("ً","ٌ","ٍ","َ","ُ","ِ","ّ","ْ"),h=new Array("آ","ا","ٱ","أ","إ","ؤ","ئ","ب","پ","ت","ث","ج","چ","ح","خ","د","ذ","ر","ز","ژ","س","ش","ص","ض","ط","ظ","ع","غ","ف","ق","ک","ك","گ","ل","م","ن","و","ه","ة","ی","ى","ي","ـ","‍"),i=new Array("ﺁ","ﺍ","ﭐ","ﺃ","ﺇ","ﺅ","ﺉ","ﺏ","ﭖ","ﺕ","ﺙ","ﺝ","ﭺ","ﺡ","ﺥ","ﺩ","ﺫ","ﺭ","ﺯ","ﮊ","ﺱ","ﺵ","ﺹ","ﺽ","ﻁ","ﻅ","ﻉ","ﻍ","ﻑ","ﻕ","ﮎ","ﻙ","ﮒ","ﻝ","ﻡ","ﻥ","ﻭ","ﻩ","ﺓ","ﯼ","ﻯ","ﻱ","ـ","‍"),j=new Array("ﺁ","ﺍ","ﭐ","ﺃ","ﺇ","ﺅ","ﺋ","ﺑ","ﭘ","ﺗ","ﺛ","ﺟ","ﭼ","ﺣ","ﺧ","ﺩ","ﺫ","ﺭ","ﺯ","ﮊ","ﺳ","ﺷ","ﺻ","ﺿ","ﻃ","ﻇ","ﻋ","ﻏ","ﻓ","ﻗ","ﮐ","ﻛ","ﮔ","ﻟ","ﻣ","ﻧ","ﻭ","ﻫ","ﻫ","ﯾ","ﻳ","ﻳ","ـ","‍"),k=new Array("ﺂ","ﺎ","ﭑ","ﺄ","ﺈ","ﺆ","ﺌ","ﺒ","ﭙ","ﺘ","ﺜ","ﺠ","ﭽ","ﺤ","ﺨ","ﺪ","ﺬ","ﺮ","ﺰ","ﮋ","ﺴ","ﺸ","ﺼ","ﻀ","ﻄ","ﻈ","ﻌ","ﻐ","ﻔ","ﻘ","ﮑ","ﻜ","ﮕ","ﻠ","ﻤ","ﻨ","ﻮ","ﻬ","ﻬ","ﯿ","ﻴ","ﻴ","ـ","‍"),l=new Array("ﺂ","ﺎ","ﭑ","ﺄ","ﺈ","ﺆ","ﺊ","ﺐ","ﭗ","ﺖ","ﺚ","ﺞ","ﭻ","ﺢ","ﺦ","ﺪ","ﺬ","ﺮ","ﺰ","ﮋ","ﺲ","ﺶ","ﺺ","ﺾ","ﻂ","ﻆ","ﻊ","ﻎ","ﻒ","ﻖ","ﮏ","ﻚ","ﮓ","ﻞ","ﻢ","ﻦ","ﻮ","ﻪ","ﺔ","ﯽ","ﻰ","ﻲ","ـ","‍"),m=null,n=null,o=null,p=b-1;for(b>0&&(m=a[p]);g.indexOf(m)>=0&&null!=m;)m=p>1?a[--p]:null;b<a.length&&(n=a[b]),b<a.length-1&&(o=a[b+1]);for(var p=b+1;g.indexOf(o)>=0&&null!=o;)o=p<a.length-1?a[++p]:null;if(h.indexOf(n)<0)return n;if(null==m||c.indexOf(m)>=0||f.indexOf(m)>=0){if(null==o||h.indexOf(o)<0||f.indexOf(o)>=0)return i[h.indexOf(n)];if(null!=o&&h.indexOf(o)>=0){if("ل"==n&&e.indexOf(o)>=0)switch(d=!0,o){case"آ":return"ﻵ";case"ا":return"ﻻ";case"أ":return"ﻷ";case"إ":return"ﻹ"}return j[h.indexOf(n)]}}else if(null!=m&&h.indexOf(m)>=0&&c.indexOf(m)<0){if(null==o||h.indexOf(o)<0||f.indexOf(o)>=0)return l[h.indexOf(n)];if(null!=o&&h.indexOf(o)>=0){if("ل"==n&&e.indexOf(o)>=0)switch(d=!0,o){case"آ":return"ﻶ";case"ا":return"ﻼ";case"أ":return"ﻸ";case"إ":return"ﻺ"}return k[h.indexOf(n)]}}}var d=!1,f=function(a){return a=a.toString(16),6===a.length?"#"+a:"#000000".substr(0,7-a.length)+a};if(fadeHex=function(a,b,c){var d=a>>16,e=a>>8&255,f=255&a;return d+=((b>>16)-d)*c,e+=((b>>8&255)-e)*c,f+=((255&b)-f)*c,d<<16|e<<8|f},strToHex=function(a){var b=0===a.indexOf("#")?a.substring(1):a;return b=parseInt("0x"+b,16)},"string"!=typeof a)throw"The first parameter should be a string";var g=a.length,h="undefined"!=typeof b&&null!=b?b:"#000000";startHex=strToHex(h);var i="undefined"!=typeof c&&null!=c?c:"#FF0000";endHex=strToHex(i);for(var j="<span style='direction:rtl; '>",k=0;k<g;k++)if(d)d=!1;else{var l=k/g,m=fadeHex(startHex,endHex,l),n=f(m);a[k];j+="<span style='color:"+n+";'>",j+=e(a,k),j+="</span>"}return j+="</span>"}
